---
output: github_document
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = T,
  comment = "#>",
  message = F,
  warning = F,
  fig.align="center",
  echo = F
)
```

# Download dos dados da de acesso a informação via LAI

Repositório para atualização da base de dados da CGU.

* Download base de dados - [clique aqui](http://www.consultaesic.cgu.gov.br/busca/_layouts/15/DownloadPedidos/DownloadDados.aspx)
* Arquivos XML baixados [clique aqui](/data-raw)
* Código em `python` para tratamento das variáveis - [clique aqui](/code)
* Arquivos tratados prontos para analisar- [clique aqui](/data-tidy)

```{r}
library(kableExtra)
library(tidyverse)

URL <- "http://www.consultaesic.cgu.gov.br/arquivosRelatorios/PedidosRespostas/Dicionario-Dados-Exportacao.txt"

dicionario <- RCurl::getURL(URL) %>% 
  str_split("\r\n") %>% 
  map(as_tibble) %>% 
  pluck(1) %>% 
  filter(!str_detect(value, "^----"), value != "") %>% 
  mutate(
    value = str_squish(value),
    Tabela = case_when(
      str_detect(value, "^--") ~ str_remove(value, "^-- CAMPOS:\\s"),
      TRUE ~ NA_character_
    ),
    Campos = case_when(
      str_detect(value, "^-\\s") ~ gsub("(^-\\s)(\\w+)(\\s-)(.+$)", "\\2", value),
      TRUE ~ NA_character_
    ),
    Formato = case_when(
      str_detect(value, "^-\\s") ~ value %>% 
        gsub("(^-\\s)(\\w+)(\\s-)(.+$)", "\\4", .) %>% 
        gsub("(^.+)(:.+$)", "\\1", .) %>% 
        str_squish(),
      TRUE ~ NA_character_
    ),
    Descricao = case_when(
      str_detect(value, "^-\\s") ~ value %>% 
        gsub("(^-\\s)(\\w+)(\\s-)(.+$)", "\\4", .) %>% 
        gsub("(^.+)(:.+$)", "\\2", .) %>%
        str_remove(":") %>% 
        str_squish(),
      TRUE ~ NA_character_
    ),
  ) %>% 
  fill(Tabela) %>% 
  na.omit() %>% 
  select(-value) 


tabela <- function(tb) {
  dicionario %>% 
    filter(Tabela == tb) %>% 
    select(-Tabela) %>% 
    kbl(caption = paste("Tabela:", tb)) %>%
    kable_styling(
      bootstrap_options = c("striped", "hover", "condensed", "responsive")
    )
}
```

```{r}
tabela("PEDIDOS")
```

```{r}
tabela("RECURSOS")
```

```{r}
tabela("SOLICITANTES")
```





```{r}
#arquivos_xml %>% purrr::map(~unzip(.x, exdir = "./data-raw"))
list.files("./data-raw", pattern = ".zip", full.names = T) 
```

```{r}
library(dplyr)
readRDS("./data-tidy/pedidos_cgu.rds") %>% glimpse()
```
